package training.day3;

public class ExceptionEx1 {
	public static void main(String [] args) {
		try {
			int n1 = Integer.parseInt(args[0]);
			int n2 = Integer.parseInt(args[1]);
			
			System.out.println("Result of division is" + (n1/n2));
		}catch(ArithmeticException e) {
			e.printStackTree();
		}catch(NumberFormatException nfe) {
			nfe.printStackTree;
		}
		System.out.println("This is some b logic");
		}
